source 'https://rubygems.org'

gem 'rails', '4.0.3'
gem 'pg'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'slim'

group :development, :test do
  gem 'rspec-rails', '~> 3.0.0.beta'
  gem 'pry'
end

group :test do
  gem 'database_cleaner', git: 'git@github.com:bmabey/database_cleaner.git'
  gem 'shoulda-matchers'
  gem 'capybara'
end

group :doc do
  gem 'sdoc', require: false
end
