development:
  adapter: postgresql
  encoding: unicode
  database: challenge_development
  pool: 5
  username: challenge
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: challenge_test
  pool: 5
  username: challenge
  password:
